# Generated by Django 3.0.5 on 2021-06-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_auto_20210616_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='imports',
            name='indenter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indenters', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='imports',
            name='partner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='imports.Customer'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='exporter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exporters', to='imports.Customer'),
        ),
    ]
