# Generated by Django 3.0.5 on 2021-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_imports_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imports',
            name='priority',
        ),
        migrations.AddField(
            model_name='imports',
            name='paymentTerm',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=4),
        ),
    ]
