# Generated by Django 3.0.5 on 2021-06-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20210616_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='priceInKg',
        ),
    ]
