# Generated by Django 3.0.5 on 2021-09-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_backaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='back_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.BackAccount'),
        ),
    ]
