# Generated by Django 3.0.5 on 2021-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20210404_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='imports',
            name='status',
            field=models.CharField(choices=[('Signed', 'Signed'), ('Unsigned', 'Unsigned'), ('Pending', 'Pending')], default='Signed', max_length=9),
        ),
    ]
