# Generated by Django 3.0.5 on 2021-04-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_imports_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blNo', models.CharField(max_length=100)),
                ('shipDate', models.DateField()),
                ('vesselName', models.CharField(max_length=70)),
                ('vesselType', models.CharField(max_length=70)),
                ('load', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='imports',
            name='shipmentDetails',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.ShipmentDetails'),
        ),
    ]
