# Generated by Django 3.0.5 on 2021-09-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_account_back_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imports/%Y/%m/%d')),
                ('imports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.Imports')),
            ],
        ),
    ]
