# Generated by Django 3.0.5 on 2021-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_auto_20210616_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='imports',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imports',
            name='netWeight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='imports',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
