# Generated by Django 3.0.5 on 2021-06-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_auto_20210616_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imports',
            name='total',
        ),
        migrations.AlterField(
            model_name='imports',
            name='netWeight',
            field=models.FloatField(),
        ),
    ]
