# Generated by Django 3.0.5 on 2021-04-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_auto_20210404_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealDate', models.DateField()),
                ('departureDate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('netWeight', models.FloatField()),
                ('price', models.IntegerField()),
                ('paymentTerm', models.IntegerField(choices=[('Cash', 'Cash'), ('Card', 'Card')])),
                ('status', models.CharField(choices=[('Signed', 'Signed'), ('Unsigned', 'Unsigned'), ('Pending', 'Pending')], max_length=100)),
                ('productDetails', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Products')),
                ('shipmentDetails', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.ShipmentDetails')),
            ],
        ),
    ]
