# Generated by Django 3.0.5 on 2021-06-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_auto_20210616_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exports',
            name='price',
        ),
        migrations.AddField(
            model_name='exports',
            name='exporter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exporterss', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='exports',
            name='indenter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indenterss', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='exports',
            name='partner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerss', to='imports.Customer'),
        ),
        migrations.AlterField(
            model_name='exports',
            name='productDetails',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Products'),
        ),
    ]
