# Generated by Django 3.0.5 on 2021-04-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_exports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealDate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('netWeight', models.FloatField()),
                ('price', models.IntegerField()),
                ('load', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('paymentTerm', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=4)),
                ('status', models.CharField(choices=[('Signed', 'Signed'), ('Unsigned', 'Unsigned'), ('Pending', 'Pending')], default='Signed', max_length=9)),
                ('productDetails', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Products')),
            ],
        ),
    ]
