# Generated by Django 3.0.5 on 2021-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_auto_20210701_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='exports',
            name='priceInKg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exports',
            name='totalPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imports',
            name='priceInKg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
