# Generated by Django 3.0.5 on 2021-05-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_exportindent_importindent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='imports',
            name='exporter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Customer'),
        ),
    ]
