# Generated by Django 3.0.5 on 2021-07-05 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0010_auto_20210705_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locals',
            name='productDetails',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Products'),
        ),
    ]
