# Generated by Django 3.0.5 on 2021-07-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0011_auto_20210705_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportindent',
            name='price',
        ),
        migrations.AddField(
            model_name='exportindent',
            name='buyer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportindentbuyer', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='exportindent',
            name='partner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportindentpartner', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='exportindent',
            name='priceInKg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportindent',
            name='seller',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportindentseller', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='exportindent',
            name='totalPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportindent',
            name='productDetails',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Products'),
        ),
    ]
