# Generated by Django 3.0.5 on 2021-07-05 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0012_auto_20210705_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importindent',
            name='price',
        ),
        migrations.AddField(
            model_name='importindent',
            name='buyer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='importindent',
            name='departureDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='importindent',
            name='partner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importindentpartner', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='importindent',
            name='priceInKg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importindent',
            name='seller',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='imports.Customer'),
        ),
        migrations.AddField(
            model_name='importindent',
            name='totalPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importindent',
            name='productDetails',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Products'),
        ),
    ]
