# Generated by Django 3.0.5 on 2021-07-25 18:53

from django.db import migrations, models
import imports.models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0016_imports_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cardNo', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='', upload_to=imports.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='imports',
            name='image',
        ),
    ]
