# Generated by Django 3.0.5 on 2021-07-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0018_imports_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapi',
            name='cardNo',
        ),
        migrations.RemoveField(
            model_name='testapi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testapi',
            name='name',
        ),
        migrations.AddField(
            model_name='testapi',
            name='contractId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
