# Generated by Django 3.0.5 on 2021-07-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0019_auto_20210727_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestApi',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='imports',
            name='image',
        ),
    ]
